/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semana7.key;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;


/**
 *
 * @author enrique
 */
public class Registro extends javax.swing.JFrame implements MouseListener, KeyListener {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        
        this.addMouseListener(this);
        this.addKeyListener(this);
    }
    
    public void mostrar() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {        
        //System.out.println("Mouse clic");
        int clics = e.getClickCount();
        
        if (clics >= 2) {
            System.out.println("Doble clic");
        }
        
        switch(e.getButton()) {
            case MouseEvent.BUTTON1 -> System.out.println("Boton izq");
            case MouseEvent.BUTTON2 -> System.out.println("Boton rueda");
            case MouseEvent.BUTTON3 -> System.out.println("Boton der");
        }
        
        System.out.printf("(x=%d, y=%d)%n", e.getX(), e.getY());
    }

    @Override
    public void mousePressed(MouseEvent e) {
        //System.out.println("Mouse presionado");
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        //System.out.println("Mouse liberado");
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        //System.out.println("Entra");
        System.out.printf("(x=%d, y=%d)%n", e.getX(), e.getY());
    }

    @Override
    public void mouseExited(MouseEvent e) {
        //System.out.println("Sale");
    }

    @Override
    public void keyTyped(KeyEvent e) {
        
        System.out.println("Type");
        System.out.println(e.getKeyChar());
        System.out.println(e.getKeyCode());
  
    }

    @Override
    public void keyPressed(KeyEvent e) {
        System.out.println("Press");
        System.out.println(e.getKeyChar());
        System.out.println(e.getKeyCode());
    }

    @Override
    public void keyReleased(KeyEvent e) {
        System.out.println("Release");
        
        switch(e.getKeyCode()) {
            case KeyEvent.VK_F2 -> jLabel1.setText("F2");
            case KeyEvent.VK_F3 -> jLabel1.setText("F3");
            case KeyEvent.VK_F4 -> jLabel1.setText("F4");
        }
    }
}
